apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  namespace: test-proj
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - image: 106061/goserver:1.0.0
        name: goserver
        ports:
        - containerPort: 80